/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CabinetPurchaseIdRouteImport } from './routes/cabinet/$purchaseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetPurchaseIdRoute = CabinetPurchaseIdRouteImport.update({
  id: '/cabinet/$purchaseId',
  path: '/cabinet/$purchaseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabinet/$purchaseId': typeof CabinetPurchaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabinet/$purchaseId': typeof CabinetPurchaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabinet/$purchaseId': typeof CabinetPurchaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cabinet/$purchaseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cabinet/$purchaseId'
  id: '__root__' | '/' | '/cabinet/$purchaseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabinetPurchaseIdRoute: typeof CabinetPurchaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet/$purchaseId': {
      id: '/cabinet/$purchaseId'
      path: '/cabinet/$purchaseId'
      fullPath: '/cabinet/$purchaseId'
      preLoaderRoute: typeof CabinetPurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabinetPurchaseIdRoute: CabinetPurchaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
